### ISSUE TITLE
ForestQC split: AttributeError: 'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by Eduardo-Auer** [avallonking/ForestQC#15]
Hello, I am experiencing some errors in "ForestQC split":

```
ForestQC set_outlier -i test.vcf.gz -m 500M

ForestQC v1.1.5.7 by Jae Hoon Sul Lab at UCLA
--Quality control on genetic variants from next-generation sequencing data using random forest

Outlier_DP threshold: 20
Outlier_GQ threshold: 51

ForestQC stat -i test.vcf.gz -o example.result.tsv -d concordance_rate_SNP.txt.gz -c gc_content_hg19.chrX.tsv -as user_features.tsv -p PedStructSeqID.txt --dp 20.0 --gq 51.0

ForestQC v1.1.5.7 by Jae Hoon Sul Lab at UCLA
--Quality control on genetic variants from next-generation sequencing data using random forest

Loading files...
Computing...
Done.

ForestQC split -i example.result.tsv -as user_features.tsv -t user_thresholds.tsv

ForestQC v1.1.5.7 by Jae Hoon Sul Lab at UCLA
--Quality control on genetic variants from next-generation sequencing data using random forest

Loading data...
Data processing...

Current filter settings:

Good variants
----------------
Mendel_Error <= 0.04478
Missing_Rate < 0.11
HWE > 0.01
0.3 <= ABHet_deviation <= 0.7

Bad variants
----------------
Rare variants (MAF < 0.02):
        Mendel_Error > 0.004
        Missing_Rate > 0.2
        HWE < 0.005
        ABHet_deviation > 0.25

Common variants (MAF >= 0.02):
        Mendel_Error > 0.07463
        Missing_Rate > 0.25
        HWE < 0.0005
        ABHet_deviation > 0.3

Outlier variants
----------------
Rare variants (MAF < 0.02):
        Mendel_Error > 0.1194
        Missing_Rate > 0.08
        HWE < 0.002

Common variants (MAF >= 0.02):
        Mendel_Error > 0.14925
        Missing_Rate > 0.12
        HWE < 1e-08
Traceback (most recent call last):
  File "/root/mambaforge-pypy3/envs/forestqc/bin/ForestQC", line 33, in <module>
    sys.exit(load_entry_point('ForestQC==1.1.5.7', 'console_scripts', 'ForestQC')())
  File "/root/mambaforge-pypy3/envs/forestqc/lib/python3.9/site-packages/ForestQC/__main__.py", line 201, in main
    command_functions[command](**args)
  File "/root/mambaforge-pypy3/envs/forestqc/lib/python3.9/site-packages/ForestQC/__main__.py", line 159, in main_split
    execute_split(input_file, output_file, model, user_feature_names, thresholds_setting)
  File "/root/mambaforge-pypy3/envs/forestqc/lib/python3.9/site-packages/ForestQC/data_preprocessing.py", line 260, in execute_split
    good, bad, grey = model_selection[model](data, thresholds_setting)
  File "/root/mambaforge-pypy3/envs/forestqc/lib/python3.9/site-packages/ForestQC/data_preprocessing.py", line 143, in separateDataB
    grey = variants.append([good, bad])
  File "/root/mambaforge-pypy3/envs/forestqc/lib/python3.9/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
```

Is there any solution for this?

**Comment by Eduardo-Auer** [comment]
No response from developer.
